# Informacoes
# Usa a imagem:8.1.0
# Trabalha na pasta /app
# Usa o MySQL como driver


# Qual imagem a ser utilizada como referência 
FROM php:8.1.0

RUN apt-get update -y && apt-get install -y openssl zip unzip git gnupg2

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /app

COPY . /app
RUN composer install
CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080